### ISSUE TITLE
The dollar symbol is being escaped when a field's name is changed

### ISSUE THREAD

**Issue by RubenGM** [MatrixDev/Roomigrant#19]
As seen in Database_Migration_3_4 after building RoomigrantTest:

`database.execSQL("INSERT INTO Object1Dbo_MERGE_TABLE (id,nullIntVal,nullStringVal,intValRenamed,stringValRenamed) SELECT Object1Dbo.id,Object1Dbo.nullIntVal,Object1Dbo.nullStringVal,${'$'}var1,${'$'}var2 FROM Object1Dbo")`

var1 and var2 are not actually being used because of this and the table's data is lost on migration.

**Comment by MatrixDev** [comment]
Hey, thanks for finding this issue.
That part needs to be heavily refactored but anyways.
I removed placeholder from your commit and changed all to %P. Also master had one PR merged that was not relevant so I had to create separate commit with the fix.
eabacbe0eb5407b9ba2bb414069b994f4c449709
