### ISSUE TITLE
Build error with version 0.3.3

### ISSUE THREAD

**Issue by SteinerOk** [MatrixDev/Roomigrant#21]
When updating version, I received:

1)  **Variable 'tableInfo' must be initialized** error, generated code with error: [https://jmp.sh/jPDooYc](url)
2) **Expecting an element** error, generated code with error: [https://jmp.sh/MowbDGG](url)

P.S.: With 0.3.2 - the same error, with 0.3.1 - all work fine.

**Comment by MatrixDev** [comment]
Thanks, found the issue. Actually two separate issues.
One should be covered by tests, don't understand why it was not caught, second - you have really long index names :)

**Comment by SteinerOk** [comment]
@MatrixDev with 0.3.4 all build fine :)

P.S.: May you remove wrong version 3.0 from jitpack, because versions plugin not work correctly?
```
 - com.github.MatrixDev.Roomigrant:RoomigrantCompiler [0.3.4 -> 3.0]
     https://github.com/MatrixDev/Roomigrant
 - com.github.MatrixDev.Roomigrant:RoomigrantLib [0.3.4 -> 3.0]
```

**Comment by MatrixDev** [comment]
@SteinerOk I don't see 3.0 version on jitpack. I did push it by mistake but removed it almost right after that.
![image](https://user-images.githubusercontent.com/1215187/111154533-fca48e80-859b-11eb-8624-6d23dcf7b49d.png)

**Comment by SteinerOk** [comment]
@MatrixDev I think plugin take info from "Build" tab: [https://jmp.sh/cu52cEJ](url)

**Comment by MatrixDev** [comment]
@SteinerOk well... I can't remove it as it is frozen at this time... I'll ask support if it can be done though.

**Comment by MatrixDev** [comment]
@SteinerOk done
